
name: Disk Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ labeled, unlabeled, opened, synchronize, reopened ]


jobs:
  disk:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: src/argocd_image_speedup
     
      
      - name: Check Disk space
        run: |
          df -h


      
